# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/808b9e43-22f8-4228-91cc-04a85bf47d82";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."vyasapura" = {
    device = "/dev/disk/by-uuid/054e48e6-808f-409f-b4d8-373c54de26c4";
    crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-measure-pcr=yes" ];
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/808b9e43-22f8-4228-91cc-04a85bf47d82";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/808b9e43-22f8-4228-91cc-04a85bf47d82";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0071-9234";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "umask=0077" "defaults" ];
    };

  fileSystems."/mnt/Lexar_SSD" =
    { device = "/dev/disk/by-uuid/d29c5ad3-c420-4cd7-94cb-ad5e86192d37";
      fsType = "btrfs";
      options = [ "subvol=primary" ];
    };

  boot.initrd.luks.devices."Lexar_SSD".device = "/dev/disk/by-uuid/6fd5fba3-3a0f-43c6-abe7-3586415f9e75";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
